import type {
  HousingListing,
  LaundryProvider,
  FoodRequest,
  SecondHandItem,
  HousingReservation,
  LaundryBooking,
} from "./types"

// Housing Listings Mock Data
export const mockHousingListings: HousingListing[] = [
  {
    id: "housing_001",
    title: "Comfortable Single Room Near Campus",
    description: "Fully furnished single room with WiFi and AC. Perfect for focused students. 5 minutes walk to campus gate.",
    price: 15000,
    location: {
      address: "123 University Road",
      city: "Colombo",
      district: "Colombo",
      distance: 0.5,
    },
    propertyType: "boarding",
    roomType: "single",
    amenities: ["WiFi", "AC", "Attached Bathroom", "Study Table", "Cupboard"],
    images: ["/placeholder.svg?height=400&width=600"],
    providerId: "user_provider_001",
    providerName: "Sarah Williams",
    contactPhone: "0771234567",
    availability: true,
    status: "approved",
    isActive: true,
    rulesAndRegulations: "No smoking. Quiet hours after 10 PM.",
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-03-15T14:30:00Z",
  },
  {
    id: "housing_002",
    title: "Spacious Shared Room with Balcony",
    description: "Share with one other student. Large balcony with garden view. Common kitchen available.",
    price: 10000,
    location: {
      address: "45 College Lane",
      city: "Colombo",
      district: "Colombo",
      distance: 0.8,
    },
    propertyType: "boarding",
    roomType: "shared",
    amenities: ["WiFi", "Hot Water", "Balcony", "Kitchen", "Parking"],
    images: ["/placeholder.svg?height=400&width=600"],
    providerId: "user_provider_002",
    providerName: "Michael Chen",
    contactPhone: "0779876543",
    availability: true,
    status: "approved",
    isActive: true,
    createdAt: "2026-02-20T09:00:00Z",
    updatedAt: "2026-03-10T11:00:00Z",
  },
  {
    id: "housing_003",
    title: "Modern Annex with Private Entrance",
    description: "Complete privacy with separate entrance. Includes kitchenette and bathroom. Ideal for postgraduate students.",
    price: 25000,
    location: {
      address: "78 Garden View",
      city: "Kandy",
      district: "Kandy",
      distance: 1.2,
    },
    propertyType: "annex",
    roomType: "single",
    amenities: ["WiFi", "AC", "Hot Water", "Kitchen", "TV", "Washing Machine"],
    images: ["/placeholder.svg?height=400&width=600"],
    providerId: "user_provider_001",
    providerName: "Sarah Williams",
    contactPhone: "0771234567",
    availability: true,
    status: "approved",
    isActive: true,
    rulesAndRegulations: "Pets not allowed. Monthly payment in advance.",
    createdAt: "2026-03-05T15:00:00Z",
    updatedAt: "2026-03-18T09:30:00Z",
  },
  {
    id: "housing_004",
    title: "Budget-Friendly Shared Accommodation",
    description: "Affordable shared room for 3 students. Great community environment. Walking distance to bus stop.",
    price: 7500,
    location: {
      address: "12 Student Street",
      city: "Colombo",
      district: "Colombo",
      distance: 1.5,
    },
    propertyType: "room",
    roomType: "shared",
    amenities: ["WiFi", "Hot Water", "Common Area"],
    images: ["/placeholder.svg?height=400&width=600"],
    providerId: "user_provider_003",
    providerName: "Priya Sharma",
    contactPhone: "0776543210",
    availability: true,
    status: "approved",
    isActive: true,
    createdAt: "2026-02-28T12:00:00Z",
    updatedAt: "2026-03-12T16:00:00Z",
  },
]

// Laundry Providers Mock Data
export const mockLaundryProviders: LaundryProvider[] = [
  {
    id: "laundry_001",
    businessName: "QuickWash Laundry",
    userId: "user_laundry_001",
    location: "Near University Gate 2",
    contactNumber: "0771111111",
    operatingHours: {
      open: "08:00",
      close: "20:00",
    },
    clothesCategories: [
      { name: "Regular / Daily Wear", pricePerPiece: 50 },
      { name: "Delicate", pricePerPiece: 80 },
      { name: "Heavy", pricePerPiece: 100 },
      { name: "Formal", pricePerPiece: 70 },
    ],
    serviceTypes: [
      { name: "Wash & Dry", price: 200 },
      { name: "Iron", price: 150 },
    ],
    serviceDurations: [
      { name: "12-hour service", price: 100 },
      { name: "24-hour service", price: 50 },
      { name: "48-hour service", price: 0 },
      { name: "Weekly service", price: 0 },
    ],
    rating: 4.5,
    totalReviews: 128,
    isActive: true,
    createdAt: "2026-01-15T10:00:00Z",
  },
  {
    id: "laundry_002",
    businessName: "Campus Clean",
    userId: "user_laundry_002",
    location: "Main Campus Road",
    contactNumber: "0772222222",
    operatingHours: {
      open: "07:00",
      close: "22:00",
    },
    clothesCategories: [
      { name: "Regular / Daily Wear", pricePerPiece: 45 },
      { name: "Delicate", pricePerPiece: 75 },
      { name: "Heavy", pricePerPiece: 90 },
      { name: "Formal", pricePerPiece: 65 },
    ],
    serviceTypes: [
      { name: "Wash & Dry", price: 180 },
      { name: "Iron", price: 120 },
    ],
    serviceDurations: [
      { name: "12-hour service", price: 80 },
      { name: "24-hour service", price: 30 },
      { name: "48-hour service", price: 0 },
    ],
    rating: 4.2,
    totalReviews: 89,
    isActive: true,
    createdAt: "2026-02-01T08:00:00Z",
  },
  {
    id: "laundry_003",
    businessName: "Fresh & Clean",
    userId: "user_laundry_003",
    location: "Behind Library Building",
    contactNumber: "0773333333",
    operatingHours: {
      open: "09:00",
      close: "18:00",
    },
    clothesCategories: [
      { name: "Regular / Daily Wear", pricePerPiece: 55 },
      { name: "Delicate", pricePerPiece: 85 },
      { name: "Heavy", pricePerPiece: 110 },
      { name: "Formal", pricePerPiece: 75 },
    ],
    serviceTypes: [
      { name: "Wash & Dry", price: 220 },
      { name: "Iron", price: 160 },
    ],
    serviceDurations: [
      { name: "24-hour service", price: 60 },
      { name: "48-hour service", price: 20 },
      { name: "Weekly service", price: 0 },
    ],
    rating: 4.8,
    totalReviews: 156,
    isActive: true,
    createdAt: "2026-01-20T11:00:00Z",
  },
]

// Food Requests Mock Data
export const mockFoodRequests: FoodRequest[] = [
  {
    id: "food_001",
    requestNumber: "FOOD-00456",
    requesterId: "user_student_002",
    requesterName: "David Lee",
    requesterContact: "0774444444",
    mealType: "Lunch",
    foodItems: [
      { item: "Rice and Curry", quantity: 1 },
      { item: "Orange Juice", quantity: 1 },
    ],
    deliveryLocation: {
      type: "Hostel",
      details: "Block A, Room 305",
    },
    requiredTime: "2026-03-20T13:00:00Z",
    status: "pending",
    paymentStatus: "pending",
    specialInstructions: "Extra spicy please",
    createdAt: "2026-03-20T11:30:00Z",
  },
  {
    id: "food_002",
    requestNumber: "FOOD-00457",
    requesterId: "user_student_003",
    requesterName: "Emma Wilson",
    requesterContact: "0775555555",
    mealType: "Dinner",
    foodItems: [
      { item: "Kottu", quantity: 1 },
      { item: "Water Bottle", quantity: 2 },
    ],
    deliveryLocation: {
      type: "Study Room",
      details: "Library Building, 2nd Floor",
    },
    requiredTime: "2026-03-20T19:00:00Z",
    status: "pending",
    paymentStatus: "pending",
    createdAt: "2026-03-20T17:00:00Z",
  },
]

// Second-Hand Items Mock Data
export const mockSecondHandItems: SecondHandItem[] = [
  {
    id: "item_001",
    title: "iPhone 13 - Excellent Condition",
    description: "Used for 1 year, no scratches, with original box and charger. Battery health 92%.",
    category: "Electronics",
    price: 85000,
    condition: "Like New",
    images: ["/placeholder.svg?height=400&width=400"],
    sellerId: "user_student_001",
    sellerName: "Alex Johnson",
    sellerContact: "0771234567",
    location: "Colombo Campus",
    status: "available",
    views: 45,
    isActive: true,
    createdAt: "2026-03-15T10:30:00Z",
    updatedAt: "2026-03-18T14:00:00Z",
  },
  {
    id: "item_002",
    title: "Engineering Mathematics Textbook Set",
    description: "Complete set of 3 books for first year engineering. Minimal highlighting. Perfect for new students.",
    category: "Books & Notes",
    price: 2500,
    condition: "Good",
    images: ["/placeholder.svg?height=400&width=400"],
    sellerId: "user_student_004",
    sellerName: "Raj Patel",
    sellerContact: "0776666666",
    location: "Engineering Faculty",
    status: "available",
    views: 32,
    isActive: true,
    createdAt: "2026-03-10T09:00:00Z",
    updatedAt: "2026-03-16T11:30:00Z",
  },
  {
    id: "item_003",
    title: "Study Desk with Chair",
    description: "Sturdy wooden desk with matching chair. Perfect for dorm room. Minor wear on corners.",
    category: "Furniture",
    price: 8000,
    condition: "Good",
    images: ["/placeholder.svg?height=400&width=400"],
    sellerId: "user_student_005",
    sellerName: "Lisa Brown",
    sellerContact: "0777777777",
    location: "Near Gate 1",
    status: "available",
    views: 28,
    isActive: true,
    createdAt: "2026-03-08T14:00:00Z",
    updatedAt: "2026-03-14T16:00:00Z",
  },
  {
    id: "item_004",
    title: "Scientific Calculator Casio FX-991",
    description: "Works perfectly. Great for engineering and science students. Includes case.",
    category: "Stationery",
    price: 3500,
    condition: "Like New",
    images: ["/placeholder.svg?height=400&width=400"],
    sellerId: "user_student_006",
    sellerName: "Mark Davis",
    sellerContact: "0778888888",
    location: "Science Faculty",
    status: "available",
    views: 56,
    isActive: true,
    createdAt: "2026-03-12T11:00:00Z",
    updatedAt: "2026-03-17T09:00:00Z",
  },
  {
    id: "item_005",
    title: "Badminton Racket Set",
    description: "2 rackets with shuttlecocks. Good condition. Great for recreation.",
    category: "Sports Equipment",
    price: 1500,
    condition: "Fair",
    images: ["/placeholder.svg?height=400&width=400"],
    sellerId: "user_student_007",
    sellerName: "Chris Taylor",
    sellerContact: "0779999999",
    location: "Sports Complex",
    status: "reserved",
    buyerName: "John Doe",
    buyerContact: "0770000001",
    reservationExpiry: "2026-03-22T10:00:00Z",
    views: 41,
    isActive: true,
    createdAt: "2026-03-05T15:00:00Z",
    updatedAt: "2026-03-20T10:00:00Z",
  },
]

// Housing Reservations Mock Data
export const mockReservations: HousingReservation[] = [
  {
    id: "reservation_001",
    listingId: "housing_001",
    studentId: "user_student_001",
    studentName: "Alex Johnson",
    checkInDate: "2026-04-01",
    duration: 12,
    totalPrice: 180000,
    status: "pending",
    message: "Looking forward to staying here for my final year",
    createdAt: "2026-03-18T10:00:00Z",
    updatedAt: "2026-03-18T10:00:00Z",
  },
]

// Laundry Bookings Mock Data
export const mockLaundryBookings: LaundryBooking[] = [
  {
    id: "booking_001",
    orderNumber: "LND-00123",
    providerId: "laundry_001",
    studentId: "user_student_001",
    studentName: "Alex Johnson",
    studentContact: "0771234567",
    clothesItems: [
      { category: "Regular / Daily Wear", quantity: 10, price: 500 },
      { category: "Formal", quantity: 3, price: 210 },
    ],
    selectedServices: ["Wash & Dry", "Iron"],
    serviceDuration: "24-hour service",
    totalPrice: 1210,
    collectionDate: "2026-03-22",
    status: "requested",
    paymentStatus: "pending",
    createdAt: "2026-03-20T09:00:00Z",
  },
]

// Helper to generate unique IDs
export function generateId(prefix: string): string {
  return `${prefix}_${Date.now()}_${Math.random().toString(36).substring(2, 9)}`
}

// Helper to generate order numbers
export function generateOrderNumber(prefix: string): string {
  const num = Math.floor(Math.random() * 99999).toString().padStart(5, "0")
  return `${prefix}-${num}`
}
